repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=750']
        exclude: ^uv.lock$
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: black
        name: black formatter
        entry: uv run black
        language: system
        types: [python]

      - id: ruff
        name: ruff linter
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]

      # - id: mypy
      #   name: mypy type check
      #   entry: uv run mypy
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   # args: [your_package_name]
      #   args: [.]
      #   require_serial: true
